version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongodb
    command: mongod --auth
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: online
    restart: 'always'

  redis:
    image: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=moment
    command: redis-server --requirepass moment
    volumes:
      - redis-data:/data
    restart: always

volumes:
  mongodata:
  config:
  redis-data:
  data:
